version: "3.7"

services:
  database:
    image: postgres
    container_name: tv-shows-app-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tv-shows-app
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
